import { getGithubResource, GIT_REPOSITORIES } from './getGithubResouce'

export const Cover: Record<string, string> = {
  // Citologia
  citology: getGithubResource(GIT_REPOSITORIES.IMAGES, "citology.jpg"),
  eukaryotic_cell: getGithubResource(GIT_REPOSITORIES.IMAGES, "eukaryotic_cell.png"),
  prokaryotic_cell: getGithubResource(GIT_REPOSITORIES.IMAGES, "prokaryotic_cell.png"),
  plant_cell: getGithubResource(GIT_REPOSITORIES.IMAGES, "plant_cell.png"),
  cytoplasmic_organelles: getGithubResource(GIT_REPOSITORIES.IMAGES, "cytoplasmic_organelles.jpg"),
  membrane_transport: getGithubResource(GIT_REPOSITORIES.IMAGES, "membrane_transport.jpg"),
  cell_cycle_mitosis: getGithubResource(GIT_REPOSITORIES.IMAGES, "cell_cycle_mitosis.jpg"),

  // Novas imagens (zoologia / biodiversidade)
  brain_coral: getGithubResource(GIT_REPOSITORIES.IMAGES, "brain-coral.jpg"),
  meduse_liriope: getGithubResource(GIT_REPOSITORIES.IMAGES, "medusa-liriope.jpg"),
  jellyfish_jelly: getGithubResource(GIT_REPOSITORIES.IMAGES, "jellyfish-jelly.jpg"),
  snail: getGithubResource(GIT_REPOSITORIES.IMAGES, "snail.jpg"),
  blue_ringed_octopus: getGithubResource(GIT_REPOSITORIES.IMAGES, "blue-ringed-octopus.jpg"),
  nautilus: getGithubResource(GIT_REPOSITORIES.IMAGES, "nautilus.jpg"),
  berbigao: getGithubResource(GIT_REPOSITORIES.IMAGES, "berbigao.jpg"),
  pseudoscorpion: getGithubResource(GIT_REPOSITORIES.IMAGES, "pseudoscorpion.jpg"),
  wolf_spider: getGithubResource(GIT_REPOSITORIES.IMAGES, "wolf-spider.jpg"),
  woodhouse: getGithubResource(GIT_REPOSITORIES.IMAGES, "woodhouse.jpg"),
  crab: getGithubResource(GIT_REPOSITORIES.IMAGES, "crab.jpg"),
  butterfly_monarca: getGithubResource(GIT_REPOSITORIES.IMAGES, "butterfly-monarca.jpg"),
  bee: getGithubResource(GIT_REPOSITORIES.IMAGES, "Bee.jpg"),
  ant: getGithubResource(GIT_REPOSITORIES.IMAGES, "ant.jpg"),
  centipede: getGithubResource(GIT_REPOSITORIES.IMAGES, "centipede.jpg"),
  seastar: getGithubResource(GIT_REPOSITORIES.IMAGES, "seastar.jpg"),
  sanddollar: getGithubResource(GIT_REPOSITORIES.IMAGES, "sanddollar.jpg"),
  tiger_shark: getGithubResource(GIT_REPOSITORIES.IMAGES, "tiger-shark.jpg"),
  ray: getGithubResource(GIT_REPOSITORIES.IMAGES, "ray.jpg"),
  barbel_comum: getGithubResource(GIT_REPOSITORIES.IMAGES, "barbel-comum.jpg"),
  salamandra: getGithubResource(GIT_REPOSITORIES.IMAGES, "salamandra.jpg"),
  tree_frog: getGithubResource(GIT_REPOSITORIES.IMAGES, "tree-frog.jpg"),
  tartaruga_cabecuda: getGithubResource(GIT_REPOSITORIES.IMAGES, "tartaruga-cabecuda.jpg"),
  lizard: getGithubResource(GIT_REPOSITORIES.IMAGES, "lizard.jpg"),
  snake: getGithubResource(GIT_REPOSITORIES.IMAGES, "snake.jpg"),
  ostrich: getGithubResource(GIT_REPOSITORIES.IMAGES, "ostrich.jpg"),
  blue_bird: getGithubResource(GIT_REPOSITORIES.IMAGES, "bluebird.jpg"),
  bat: getGithubResource(GIT_REPOSITORIES.IMAGES, "bat.jpg"),
  giraffe: getGithubResource(GIT_REPOSITORIES.IMAGES, "giraffe.jpg"),
  lion: getGithubResource(GIT_REPOSITORIES.IMAGES, "lion.jpg"),
  blue_whale: getGithubResource(GIT_REPOSITORIES.IMAGES, "blue-whale.jpg"),
  dolphin: getGithubResource(GIT_REPOSITORIES.IMAGES, "dolphin.jpg"),
  red_tailed_hawk: getGithubResource(GIT_REPOSITORIES.IMAGES, "red-tailed-hawk.jpg"),

  // Humana Anatomy
  endocrine_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "endocrine-system.png"),
  lymphatic_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "lymphatic-system.png"),
  muscular_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "muscular-system.png"),
  nervous_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "nervous-system.png"),
  respiratory_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "respiratory-system.png"),
  skeletal_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "skeletal-system.png"),
  urinary_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "urinary-system.png"),
  circulatory_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "circulatory-system.png"),
  digestive_system: getGithubResource(GIT_REPOSITORIES.IMAGES, "digestive-system.png"),
  
  
} as const
